### ISSUE TITLE
update_nowcasts.R breaks due to missing column

### ISSUE THREAD

**Issue by timetheoretical** [epiforecasts/covid-global#3]
Hi, thanks a lot for this great project!

I have tried to clone the [covid](https://github.com/epiforecasts/covid) project according to the descriptions of the main readme page, and then run `update_nowcasts.R` in covid-global with a view to obtain updated nowcasts in the `covid_global/national-summary/rt.csv` file.

However, when trying to run `EpiNow::regional_rt_pipeline` at line 66, I am faced with the following error message:
```R
Running pipeline for 2020-05-13
Error in `[.data.table`(data.table::copy(cases), , .(confirm = sum(confirm,  : 
  object 'confirm' not found
```

When looking at the function definition of [regional_rt_pipeline](https://github.com/epiforecasts/EpiNow/blob/master/R/regional_rt_pipeline.R), line 4, it seems that the function expects a column named `confirm`, which is not present in the `cases` dataset that is generated in the `update_nowcasts.R` script. 

I am wondering whether the `cases` column should be renamed to `confirm`. Doing so seem to "get around" the problem described above, but leads to a new error message:
```R
Error in rep("lognorm", samples) : invalid 'times' argument
```

But that is perhaps another issue.

**Comment by timetheoretical** [comment]
I am closing this issue as it has been resolved in light of the recent changes to the code.

**Comment by seabbs** [comment]
Hi @timetheoretical, 

Sorry I didn't get to this earlier but thank you for flagging the problem. Hopefully, the current data requirements are clear and everything is working as expected.

Sam

**Comment by timetheoretical** [comment]
No worries, and thanks for following this up! The script now seems to work as expected.
